name: Build android
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: depot-ubuntu-24.04-64
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: valeriangalliat/action-sshd-cloudflared@v3

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chromium-android-arm64
        path: /mnt/up
